version: '3'
services:
  javaps:
    build: .
    image: registry.wacodis.demo.52north.org/javaps:2019-07-01
    env_file:
      - wacodis.env
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G