version: '3'
services:
  javaps:
    build: .
    image: wacodis/wps
    env_file:
      - wacodis.env
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    volumes:
      - ./config/configuration.json:/usr/local/tomcat/webapps/wacodis-wps/WEB-INF/config/configuration.json
      - ./config/tools:/tmp/tools
      - ./config/gpf:/tmp/gpf
      - ./outputs:/tmp/workdir
      - /var/run/docker.sock:/var/run/docker.sock